--Global array with all data of this addon
if FCOIS == nil then FCOIS = {} end
local FCOIS = FCOIS

--==========================================================================================================================================
--									FCOIS texture names
--==========================================================================================================================================
--The textures for the marker icons
FCOIS.textureVars.MARKER_TEXTURES = {
    [1]  = [[/esoui/art/campaign/campaignbrowser_fullpop.dds]],
    [2]  = [[/esoui/art/inventory/inventory_tabicon_armor_disabled.dds]],
    [3]  = [[/esoui/art/crafting/smithing_tabicon_research_disabled.dds]],
    [4]  = [[/esoui/art/tradinghouse/tradinghouse_sell_tabicon_disabled.dds]],
    [5]  = [[/esoui/art/campaign/overview_indexicon_bonus_disabled.dds]],
    [6]  = [[/esoui/art/ava/tabicon_bg_score_disabled.dds]],
    [7]  = [[/esoui/art/guild/guild_rankicon_leader_large.dds]],
    [8]  = [[/esoui/art/lfg/lfg_healer_up.dds]],
    [9]  = [[/esoui/art/mounts/timer_icon.dds]],
    [10] = [[/esoui/art/crafting/alchemy_tabicon_solvent_up.dds]],
    [11] = [[/esoui/art/buttons/cancel_up.dds]],
    [12] = [[/esoui/art/buttons/info_up.dds]],
    [13] = [[/esoui/art/buttons/pinned_normal.dds]],
    [14] = [[/esoui/art/cadwell/cadwell_indexicon_gold_up.dds]],
    [15] = [[/esoui/art/cadwell/cadwell_indexicon_silver_up.dds]],
    [16] = [[/esoui/art/campaign/campaignbonus_keepicon.dds]],
    [17] = [[/esoui/art/icons/scroll_005.dds]],
    [18] = [[/esoui/art/campaign/campaignbrowser_columnheader_ad.dds]],
    [19] = [[/esoui/art/campaign/campaignbrowser_columnheader_dc.dds]],
    [20] = [[/esoui/art/campaign/campaignbrowser_columnheader_ep.dds]],
    [21] = [[/esoui/art/campaign/campaignbrowser_guild.dds]],
    [22] = [[/esoui/art/campaign/campaignbrowser_indexicon_normal_up.dds]],
    [23] = [[/esoui/art/campaign/overview_indexicon_scoring_up.dds]],
    [24] = [[/esoui/art/charactercreate/charactercreate_bodyicon_up.dds]],
    [25] = [[/esoui/art/characterwindow/gearslot_offhand.dds]],
    [26] = [[/esoui/art/characterwindow/gearslot_mainhand.dds]],
    [27] = [[/esoui/art/characterwindow/gearslot_costume.dds]],
    [28] = [[/esoui/art/chatwindow/chat_mail_up.dds]],
    [29] = [[/esoui/art/chatwindow/chat_notification_up.dds]],
    [30] = [[/esoui/art/crafting/alchemy_tabicon_reagent_up.dds]],
    [31] = [[/esoui/art/crafting/smithing_tabicon_refine_up.dds]],
    [32] = [[/esoui/art/deathrecap/deathrecap_killingblow_icon.dds]],
    [33] = [[/esoui/art/fishing/bait_emptyslot.dds]],
    [34] = [[/esoui/art/guild/guildhistory_indexicon_guildbank_up.dds]],
    [35] = [[/esoui/art/guild/guild_indexicon_member_up.dds]],
    [36] = [[/esoui/art/guild/tabicon_roster_up.dds]],
    [37] = [[/esoui/art/icons/poi/poi_dungeon_complete.dds]],
    [38] = [[/esoui/art/icons/poi/poi_groupinstance_complete.dds]],
    [39] = [[/esoui/art/icons/servicemappins/servicepin_magesguild.dds]],
    [40] = [[/esoui/art/icons/servicemappins/servicepin_fightersguild.dds]],
    [41] = [[/esoui/art/lfg/lfg_dps_up.dds]],
    [42] = [[/esoui/art/lfg/lfg_leader_icon.dds]],
    [43] = [[/esoui/art/lfg/lfg_tank_up.dds]],
    [44] = [[/esoui/art/lfg/lfg_veterandungeon_up.dds]],
    [45] = [[/esoui/art/lfg/lfg_normaldungeon_up.dds]],
    [46] = [[/esoui/art/progression/icon_dualwield.dds]],
    [47] = [[/esoui/art/progression/icon_firestaff.dds]],
    [48] = [[/esoui/art/progression/icon_bows.dds]],
    [49] = [[/esoui/art/progression/icon_2handed.dds]],
    [50] = [[/esoui/art/progression/icon_1handed.dds]],
    [51] = [[/esoui/art/progression/progression_tabicon_backup_inactive.dds]],
    [52] = [[/esoui/art/repair/inventory_tabicon_repair_disabled.dds]],
    [53] = [[/esoui/art/worldmap/selectedquesthighlight.dds]],
    [54] = [[/esoui/art/journal/journal_tabicon_cadwell_up.dds]],
    [55] = [[/esoui/art/crafting/enchantment_tabicon_deconstruction_disabled.dds]],
    [56] = [[/esoui/art/crafting/smithing_tabicon_improve_disabled.dds]],
    [57] = [[/esoui/art/bank/bank_tabicon_deposit_up.dds]],
    [58] = [[/esoui/art/currency/currency_gold.dds]],
    [59] = [[/esoui/art/guild/guild_bankaccess.dds]],
    [60] = [[/esoui/art/progression/progression_indexicon_guilds_up.dds]],
    --Added with FCOIS version 1.2.1
    [61] = [[esoui/art/buttons/accept_up.dds]],
    [62] = [[esoui/art/buttons/checkbox_checked.dds]],
    [63] = [[esoui/art/buttons/checkbox_indeterminate.dds]],
    [64] = [[esoui/art/buttons/dropbox_arrow_normal.dds]],
    [65] = [[esoui/art/buttons/decline_up.dds]],
    [66] = [[esoui/art/buttons/edit_cancel_up.dds]],
    [67] = [[esoui/art/buttons/edit_up.dds]],
    [68] = [[esoui/art/buttons/edit_save_up.dds]],
    [69] = [[esoui/art/buttons/gamepad/console-widget-slider.dds]],
    [70] = [[esoui/art/buttons/gamepad/console-widget-stepper.dds]],
    [71] = [[esoui/art/buttons/gamepad/gp_checkbox_down.dds]],
    [72] = [[esoui/art/buttons/gamepad/gp_checkbox_up.dds]],
    [73] = [[esoui/art/buttons/gamepad/gp_downarrow.dds]],
    [74] = [[esoui/art/buttons/gamepad/gp_menu_rightarrow.dds]],
    [75] = [[esoui/art/buttons/gamepad/gp_uparrow.dds]],
    [76] = [[esoui/art/buttons/gamepad/gp_spinnerlr.dds]],
    [77] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_circle.dds]],
    [78] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_ls.dds]],
    [79] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_rs.dds]],
    [80] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_share.dds]],
    [81] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_square.dds]],
    [82] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_trackpad_circle.dds]],
    [83] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_trackpad_leftright.dds]],
    [84] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_trackpad_lefttoright.dds]],
    [85] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_triangle.dds]],
    [86] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_trackpad_updown.dds]],
    [87] = [[esoui/art/buttons/gamepad/ps4/nav_ps4_x.dds]],
    [88] = [[esoui/art/buttons/gamepad/xbox/leftarrow_down.dds]],
    [89] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_a.dds]],
    [90] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_b.dds]],
    [91] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_rightarrow_down_hold.dds]],
    [92] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_rs_menu.dds]],
    [93] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_x.dds]],
    [94] = [[esoui/art/buttons/gamepad/xbox/nav_xbone_y.dds]],
    [95] = [[esoui/art/buttons/radiobuttonup.dds]],
    [96] = [[esoui/art/buttons/radiobuttondown.dds]],
    [97] = [[esoui/art/buttons/smoothsliderbutton_up.dds]],
    [98] = [[esoui/art/buttons/swatchframe_selected.dds]],
    [99] = [[esoui/art/buttons/switch_disabled.dds]],
    [100] = [[esoui/art/buttons/unpinned_normal.dds]],
}

--The variable for the maximum of the texture icons
FCOIS.numVars.maxTextureIcons = #FCOIS.textureVars.MARKER_TEXTURES or 100

--Additional size for the textures, if the texture got a special size
-- Used at the filter buttons e.g.
FCOIS.textureVars.MARKER_TEXTURES_SIZE = {
    --[51] = { width = 32, height = 32, offsetLeft = 0, offsetTop = 0, contextMenuOffsetLeft = 0, contextMenuOffsetTop = 0 },   --
    [27] = { width = 0, height = 0, offsetLeft = 0, offsetTop = 0, contextMenuOffsetLeft = 1, contextMenuOffsetTop = 0 },       -- Costume cloathes hanger
    [58] = { width = 16, height = 16, offsetLeft = 1, offsetTop = -19, contextMenuOffsetLeft = 1, contextMenuOffsetTop = -19 }, -- Single coin icon
}